name: Compile

on:
  push:
    branches: [ "*" ]

jobs:
  Compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev -y

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake . -G "MinGW Makefiles"
        working-directory: plugins/J3

      - name: Configure CMake (*nix)
        if: runner.os != 'Windows'
        run: cmake .
        working-directory: plugins/J3

      - name: Compile plugin
        run: cmake --build .
        working-directory: plugins/J3

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{runner.os}} Binaries
          path: plugins/J3/64/*.xpl